/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.ArbolAVL;
import Clases.ArbolBinario;
import Clases.EncriptarArchivo;
import Clases.LeerArchivo;
import Clases.NodoAVL;
import Clases.NodoArbol;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class MenuPrincipal extends javax.swing.JFrame {
    public NodoArbol nodoEncontrado;
    
    ArbolBinario arbolito;
    ArbolAVL arbolitoAVL;
    private ActualizarBBT act;
    private ActualizarAVL actAVL;
    EncriptarArchivo encrip = new EncriptarArchivo();
    
    /**
     * Creates new form MenuPrincipal
     */
    
    
    public MenuPrincipal() {
        initComponents();
        this.arbolito = ArbolBinario.getInstance();
        this.arbolitoAVL = ArbolAVL.getInstance();
        this.act = new ActualizarBBT(); 
        this.actAVL = new ActualizarAVL();
        arbolito.dibujarGraphviz();
        
     
        
    }

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        agregarBBT = new javax.swing.JButton();
        buscarBBT = new javax.swing.JButton();
        eliminarBBT = new javax.swing.JButton();
        txtBTT = new javax.swing.JTextField();
        imgBBT = new javax.swing.JLabel();
        actualizarBBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        inOrdBBT = new javax.swing.JButton();
        preOrdBBT = new javax.swing.JButton();
        postBBT = new javax.swing.JButton();
        Graphviz_BBT = new javax.swing.JButton();
        btnEncriptar = new javax.swing.JButton();
        btnDesincriptar = new javax.swing.JButton();
        btnGrabarArchivoBBT = new javax.swing.JButton();
        btnCargarArchivo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnBuscarAVL = new javax.swing.JButton();
        btnEliminarAVL = new javax.swing.JButton();
        txtAVL = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();
        btnModAVL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreAVL = new javax.swing.JTextArea();
        btnInOrdAVL = new javax.swing.JButton();
        btnPreOrnAVL = new javax.swing.JButton();
        btnPostAVL = new javax.swing.JButton();
        agregarAVL = new javax.swing.JButton();
        btnIMGAVL = new javax.swing.JButton();
        btnEncripAVL = new javax.swing.JButton();
        btnDesencripAVL = new javax.swing.JButton();
        grabarAVL = new javax.swing.JButton();
        cargarAVL = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cargarArchivoBBT = new javax.swing.JMenuItem();
        cargarArchivoAVL = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        agregarBBT.setBackground(new java.awt.Color(0, 153, 204));
        agregarBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarBBT.setForeground(new java.awt.Color(255, 255, 255));
        agregarBBT.setText("Agregar");
        agregarBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBBTActionPerformed(evt);
            }
        });

        buscarBBT.setBackground(new java.awt.Color(0, 153, 204));
        buscarBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarBBT.setForeground(new java.awt.Color(255, 255, 255));
        buscarBBT.setText("Buscar");
        buscarBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBBTActionPerformed(evt);
            }
        });

        eliminarBBT.setBackground(new java.awt.Color(0, 153, 204));
        eliminarBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarBBT.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBBT.setText("Eliminar");
        eliminarBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBBTActionPerformed(evt);
            }
        });

        txtBTT.setBackground(new java.awt.Color(255, 255, 255));

        imgBBT.setBackground(new java.awt.Color(255, 0, 204));
        imgBBT.setForeground(new java.awt.Color(51, 153, 255));
        imgBBT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arbol Binario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        actualizarBBT.setBackground(new java.awt.Color(0, 153, 204));
        actualizarBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actualizarBBT.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBBT.setText("Actualizar");
        actualizarBBT.setEnabled(false);
        actualizarBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBBTActionPerformed(evt);
            }
        });

        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        txtArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane1.setViewportView(txtArea1);

        inOrdBBT.setBackground(new java.awt.Color(0, 153, 204));
        inOrdBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inOrdBBT.setForeground(new java.awt.Color(255, 255, 255));
        inOrdBBT.setText("InOrden");
        inOrdBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inOrdBBTActionPerformed(evt);
            }
        });

        preOrdBBT.setBackground(new java.awt.Color(0, 153, 204));
        preOrdBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        preOrdBBT.setForeground(new java.awt.Color(255, 255, 255));
        preOrdBBT.setText("PreOrden");
        preOrdBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrdBBTActionPerformed(evt);
            }
        });

        postBBT.setBackground(new java.awt.Color(0, 153, 204));
        postBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        postBBT.setForeground(new java.awt.Color(255, 255, 255));
        postBBT.setText("PostOrden");
        postBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBBTActionPerformed(evt);
            }
        });

        Graphviz_BBT.setBackground(new java.awt.Color(0, 153, 204));
        Graphviz_BBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Graphviz_BBT.setForeground(new java.awt.Color(255, 255, 255));
        Graphviz_BBT.setText("BBT IMG");
        Graphviz_BBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Graphviz_BBTActionPerformed(evt);
            }
        });

        btnEncriptar.setBackground(new java.awt.Color(0, 153, 204));
        btnEncriptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncriptar.setForeground(new java.awt.Color(255, 255, 255));
        btnEncriptar.setText("Encriptar");
        btnEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptarActionPerformed(evt);
            }
        });

        btnDesincriptar.setBackground(new java.awt.Color(0, 153, 204));
        btnDesincriptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDesincriptar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesincriptar.setText("Desencriptar");
        btnDesincriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesincriptarActionPerformed(evt);
            }
        });

        btnGrabarArchivoBBT.setBackground(new java.awt.Color(0, 153, 204));
        btnGrabarArchivoBBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGrabarArchivoBBT.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabarArchivoBBT.setText("Grabar Archivo");
        btnGrabarArchivoBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarArchivoBBTActionPerformed(evt);
            }
        });

        btnCargarArchivo.setBackground(new java.awt.Color(0, 153, 204));
        btnCargarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(agregarBBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarBBT)
                                .addGap(12, 12, 12)
                                .addComponent(eliminarBBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(actualizarBBT))
                            .addComponent(imgBBT, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(Graphviz_BBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEncriptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesincriptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGrabarArchivoBBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCargarArchivo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(inOrdBBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preOrdBBT)
                        .addGap(12, 12, 12)
                        .addComponent(postBBT))
                    .addComponent(jScrollPane1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgBBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBBT)
                    .addComponent(buscarBBT)
                    .addComponent(eliminarBBT)
                    .addComponent(txtBTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarBBT)
                    .addComponent(inOrdBBT)
                    .addComponent(preOrdBBT)
                    .addComponent(postBBT))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Graphviz_BBT)
                    .addComponent(btnEncriptar)
                    .addComponent(btnDesincriptar)
                    .addComponent(btnGrabarArchivoBBT)
                    .addComponent(btnCargarArchivo))
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("BBT", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnBuscarAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnBuscarAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAVL.setText("Buscar");
        btnBuscarAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAVLActionPerformed(evt);
            }
        });

        btnEliminarAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnEliminarAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarAVL.setText("Eliminar");
        btnEliminarAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAVLActionPerformed(evt);
            }
        });

        txtAVL.setBackground(new java.awt.Color(255, 255, 255));

        imgLabel.setBackground(new java.awt.Color(255, 0, 204));
        imgLabel.setForeground(new java.awt.Color(51, 153, 255));
        imgLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arbol AVL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        btnModAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnModAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnModAVL.setText("Actualizar");
        btnModAVL.setEnabled(false);
        btnModAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAVLActionPerformed(evt);
            }
        });

        txtAreAVL.setColumns(20);
        txtAreAVL.setRows(5);
        txtAreAVL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane2.setViewportView(txtAreAVL);

        btnInOrdAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnInOrdAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInOrdAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnInOrdAVL.setText("InOrden");
        btnInOrdAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdAVLActionPerformed(evt);
            }
        });

        btnPreOrnAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnPreOrnAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPreOrnAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnPreOrnAVL.setText("PreOrden");
        btnPreOrnAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrnAVLActionPerformed(evt);
            }
        });

        btnPostAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnPostAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPostAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnPostAVL.setText("PostOrden");
        btnPostAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostAVLActionPerformed(evt);
            }
        });

        agregarAVL.setBackground(new java.awt.Color(0, 153, 204));
        agregarAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarAVL.setForeground(new java.awt.Color(255, 255, 255));
        agregarAVL.setText("Agregar");
        agregarAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAVLActionPerformed(evt);
            }
        });

        btnIMGAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnIMGAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIMGAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnIMGAVL.setText("AVL IMG");
        btnIMGAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIMGAVLActionPerformed(evt);
            }
        });

        btnEncripAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnEncripAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncripAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnEncripAVL.setText("Encriptar");
        btnEncripAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncripAVLActionPerformed(evt);
            }
        });

        btnDesencripAVL.setBackground(new java.awt.Color(0, 153, 204));
        btnDesencripAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDesencripAVL.setForeground(new java.awt.Color(255, 255, 255));
        btnDesencripAVL.setText("Desencriptar");
        btnDesencripAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesencripAVLActionPerformed(evt);
            }
        });

        grabarAVL.setBackground(new java.awt.Color(0, 153, 204));
        grabarAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        grabarAVL.setForeground(new java.awt.Color(255, 255, 255));
        grabarAVL.setText("Grabar archivo");
        grabarAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarAVLActionPerformed(evt);
            }
        });

        cargarAVL.setBackground(new java.awt.Color(0, 153, 204));
        cargarAVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cargarAVL.setForeground(new java.awt.Color(255, 255, 255));
        cargarAVL.setText("Cargar Archivo");
        cargarAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarAVLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnIMGAVL)
                                .addGap(18, 18, 18)
                                .addComponent(btnEncripAVL)
                                .addGap(30, 30, 30)
                                .addComponent(btnDesencripAVL))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(agregarAVL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarAVL)
                                .addGap(12, 12, 12)
                                .addComponent(btnEliminarAVL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModAVL)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnInOrdAVL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPreOrnAVL)
                        .addGap(12, 12, 12)
                        .addComponent(btnPostAVL))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(grabarAVL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cargarAVL)
                        .addGap(13, 13, 13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarAVL)
                    .addComponent(btnEliminarAVL)
                    .addComponent(txtAVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModAVL)
                    .addComponent(btnInOrdAVL)
                    .addComponent(btnPreOrnAVL)
                    .addComponent(btnPostAVL)
                    .addComponent(agregarAVL))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIMGAVL)
                    .addComponent(btnEncripAVL)
                    .addComponent(btnDesencripAVL)
                    .addComponent(grabarAVL)
                    .addComponent(cargarAVL))
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("AVL", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Menu");

        cargarArchivoBBT.setText("Cargar Archivo BBT");
        cargarArchivoBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoBBTActionPerformed(evt);
            }
        });
        jMenu1.add(cargarArchivoBBT);

        cargarArchivoAVL.setText("Cargar Archivo AVL");
        cargarArchivoAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoAVLActionPerformed(evt);
            }
        });
        jMenu1.add(cargarArchivoAVL);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBBTActionPerformed
        String var = txtBTT.getText();
        long dpi = Long.parseLong(var);
        arbolito.AgregarNodo(dpi, "", "", "", "", "", "", "", "");
        txtBTT.setText("");
    }//GEN-LAST:event_agregarBBTActionPerformed

    private void inOrdBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inOrdBBTActionPerformed
        StringBuilder dat = new StringBuilder();
        txtArea1.setText("");
        if (arbolito != null && !arbolito.EstaVacio()) {
            arbolito.InOrden(arbolito.raiz, dat);
        }
        txtArea1.setText(dat.toString());
    }//GEN-LAST:event_inOrdBBTActionPerformed

    private void preOrdBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrdBBTActionPerformed
        StringBuilder dat = new StringBuilder();
        txtArea1.setText("");
        if (arbolito != null && !arbolito.EstaVacio()) {
            arbolito.PreOrden(arbolito.raiz, dat);
        }
        txtArea1.setText(dat.toString());
    }//GEN-LAST:event_preOrdBBTActionPerformed

    private void postBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBBTActionPerformed
        StringBuilder dat = new StringBuilder();
        txtArea1.setText("");
        if (arbolito != null && !arbolito.EstaVacio()) {
            arbolito.PostOrden(arbolito.raiz, dat);
        }
        txtArea1.setText(dat.toString());
    }//GEN-LAST:event_postBBTActionPerformed

    private void buscarBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBBTActionPerformed
        
        if (!arbolito.EstaVacio()) {
            String bsc = txtBTT.getText();
            long dpi = Long.parseLong(bsc);
            NodoArbol tmp;
            tmp = arbolito.BuscarNodo(dpi);
            txtBTT.setText("");
            if (tmp == null) {
                txtArea1.setText("El nodo buscado no se encuentra en el arbol" + "No_Encontrado");

            } else {
                String strDat = String.valueOf(dpi);
                txtArea1.setText("Nodo enncontrado, sus datos son: " + dpi);
                nodoEncontrado = tmp;
                actualizarBBT.setEnabled(true);
            }
        } else {
            txtArea1.setText("El arbol esta vacio");
        }
        
    }//GEN-LAST:event_buscarBBTActionPerformed

    
    private void eliminarBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBBTActionPerformed
        String bsc = txtBTT.getText();
        long dpi = Long.parseLong(bsc);
        txtBTT.setText("");
        if (!arbolito.EstaVacio()) {
            if (arbolito.EliminarNodo(dpi) == false) {
                txtArea1.setText("Nodo no Encontrado");
            } else {
                txtArea1.setText("El Nodo Eliminado");
            }
        } else {
            txtArea1.setText("El Arbol esta vacio");
        }
    }//GEN-LAST:event_eliminarBBTActionPerformed

    private void Graphviz_BBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Graphviz_BBTActionPerformed
    arbolito.dibujarGraphviz();
    String path = "arbl.png";
    
    // Verifica que la ruta sea correcta
    File file = new File(path);
    if (file.exists()) {
        ImageIcon ic = new ImageIcon(path);
        Image nw = ic.getImage().getScaledInstance(imgBBT.getWidth(), imgBBT.getHeight(), Image.SCALE_SMOOTH); 
        ImageIcon nc = new ImageIcon(nw);
        imgBBT.setIcon(nc);
    } else {
        System.out.println("La imagen no existe en la ruta especificada: " + path);
    }
    }//GEN-LAST:event_Graphviz_BBTActionPerformed

    private void btnEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptarActionPerformed
        try {
            encrip.encriptarTodos(arbolito.raiz);
            encrip.encriptarArchivo(encrip.getMiArchivoBBT());
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_btnEncriptarActionPerformed

    
    
    //-------------------------CODIGO DE AVL ---------------------------------------------------------
    
    
    
    private void agregarAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAVLActionPerformed
        String varAVL = txtAVL.getText();
        long dpi = Long.parseLong(varAVL);
        arbolitoAVL.insertarNodo(dpi,"", "", "", "", "", "", "", "");
        txtAVL.setText("");               
    }//GEN-LAST:event_agregarAVLActionPerformed

    private void btnBuscarAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAVLActionPerformed
         if (!arbolitoAVL.estaVacioElArbol()) {
            String bsc = txtAVL.getText();
            long dpi = Long.parseLong(bsc);
            NodoAVL tmp;
            tmp = arbolitoAVL.buscar(dpi, arbolitoAVL.raiz);
            txtAVL.setText("");
            if (tmp == null) {
                txtAreAVL.setText("El nodo buscado no se encuentra**");

            } else {
                String strDat = String.valueOf(dpi);
                txtAreAVL.setText("Nodo enncontrado sus datos son: " + dpi);
              
                btnModAVL.setEnabled(true);
            }
        } else {
            txtAreAVL.setText("El arbol esta vacio");
        }
    }//GEN-LAST:event_btnBuscarAVLActionPerformed

    
    private void btnEliminarAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAVLActionPerformed
        
        String bsc = txtAVL.getText();
        long dpi = Long.parseLong(bsc);
        txtAVL.setText("");
        if (!arbolitoAVL.estaVacioElArbol()) {
            if (arbolitoAVL.buscar(dpi, arbolitoAVL.raiz) == null){
                txtAreAVL.setText("Nodo no Encontrado");
            } else {
                arbolitoAVL.setRaiz(arbolitoAVL.eliminarNodo(arbolitoAVL.raiz, dpi));
                txtAreAVL.setText("El Nodo Eliminado");
            }
        } else {
            txtAreAVL.setText("El Arbol esta vacio");
        } 
        
    }//GEN-LAST:event_btnEliminarAVLActionPerformed

    private void btnModAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAVLActionPerformed
        this.setVisible(false);
        actAVL.setVisible(true);
        actAVL.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnModAVLActionPerformed

    private void btnInOrdAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdAVLActionPerformed
        StringBuilder dat = new StringBuilder();
        txtAreAVL.setText("");
        if (arbolitoAVL != null && !arbolitoAVL.estaVacioElArbol()) {
            arbolitoAVL.Enorden(arbolitoAVL.raiz, dat);
        }
        txtAreAVL.setText(dat.toString());
    }//GEN-LAST:event_btnInOrdAVLActionPerformed

    private void btnPreOrnAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrnAVLActionPerformed
        StringBuilder dat = new StringBuilder();
        txtAreAVL.setText("");
        if (arbolitoAVL != null && !arbolitoAVL.estaVacioElArbol()) {
            arbolitoAVL.preorden(arbolitoAVL.raiz, dat);
        }
        txtAreAVL.setText(dat.toString());
    }//GEN-LAST:event_btnPreOrnAVLActionPerformed

    private void btnPostAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostAVLActionPerformed
        StringBuilder dat = new StringBuilder();
        txtAreAVL.setText("");
        if (arbolitoAVL != null && !arbolitoAVL.estaVacioElArbol()) {
            arbolitoAVL.PostOrden(arbolitoAVL.raiz, dat);
        }
        txtAreAVL.setText(dat.toString());
    }//GEN-LAST:event_btnPostAVLActionPerformed

    private void actualizarBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBBTActionPerformed
        this.setVisible(false);
        act.setVisible(true);
        act.setLocationRelativeTo(null);
    }//GEN-LAST:event_actualizarBBTActionPerformed

    private void btnGrabarArchivoBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarArchivoBBTActionPerformed
        try {
        if (arbolito.EstaVacio()) {
            JOptionPane.showMessageDialog(this, "El árbol binario está vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            arbolito.cargarArchivoBBT();
        }
    } catch (Exception e) {
        // Maneja la excepción aquí
        JOptionPane.showMessageDialog(this, "Ocurrió un error al cargar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGrabarArchivoBBTActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        encrip.cargar(arbolito);
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnDesincriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesincriptarActionPerformed
      
        try {
            encrip.desencriptarTodos(arbolito.raiz);
            encrip.desencriptarArchivo(encrip.getMiArchivoBBT());
        }catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDesincriptarActionPerformed

    private void grabarAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarAVLActionPerformed
        try {
        if (arbolitoAVL.estaVacioElArbol()) {
            JOptionPane.showMessageDialog(this, "El árbol binario está vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            arbolitoAVL.cargarArchivoAVL();
        }
    } catch (Exception e) {
        // Maneja la excepción aquí
        JOptionPane.showMessageDialog(this, "Ocurrió un error al cargar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_grabarAVLActionPerformed

    private void cargarAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarAVLActionPerformed
        encrip.cargarAVL(arbolitoAVL);
    }//GEN-LAST:event_cargarAVLActionPerformed

    private void btnIMGAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIMGAVLActionPerformed
        arbolitoAVL.dibujarGraphviz();
    String path = "arblAVL.png";
    
    // Verifica que la ruta sea correcta
    File file = new File(path);
    if (file.exists()) {
        ImageIcon ic = new ImageIcon(path);
        Image nw = ic.getImage().getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), Image.SCALE_SMOOTH); 
        ImageIcon nc = new ImageIcon(nw);
        imgLabel.setIcon(nc);
    } else {
        System.out.println("La imagen no existe en la ruta especificada: " + path);
    }
    }//GEN-LAST:event_btnIMGAVLActionPerformed

    private void btnEncripAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncripAVLActionPerformed
        try {
            encrip.encriptarAVL(arbolitoAVL.raiz);
            encrip.encriptarArchivo(encrip.getMiArchivoAVL());
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_btnEncripAVLActionPerformed

    private void btnDesencripAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencripAVLActionPerformed
        try {
            encrip.desencriptarAVL(arbolitoAVL.raiz);
            encrip.desencriptarArchivo(encrip.getMiArchivoAVL());
        }catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDesencripAVLActionPerformed

    
    //CODIGO DE BBT
    private void cargarArchivoBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoBBTActionPerformed
        LeerArchivo arch = new LeerArchivo();
        JFileChooser fileChooser = new JFileChooser();
        int rps = fileChooser.showOpenDialog(null);

        File fich = fileChooser.getSelectedFile();
        arch.leerArch(arbolito, fich);

    }//GEN-LAST:event_cargarArchivoBBTActionPerformed

    
    //CODIGO DE AVL
    private void cargarArchivoAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoAVLActionPerformed
        LeerArchivo arch = new LeerArchivo();
        JFileChooser fileChooser = new JFileChooser();
        int rps = fileChooser.showOpenDialog(null);

        File fich = fileChooser.getSelectedFile();
        arch.leerArchAVL(arbolitoAVL, fich);
    }//GEN-LAST:event_cargarArchivoAVLActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Graphviz_BBT;
    private javax.swing.JButton actualizarBBT;
    private javax.swing.JButton agregarAVL;
    private javax.swing.JButton agregarBBT;
    private javax.swing.JButton btnBuscarAVL;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnDesencripAVL;
    private javax.swing.JButton btnDesincriptar;
    private javax.swing.JButton btnEliminarAVL;
    private javax.swing.JButton btnEncripAVL;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JButton btnGrabarArchivoBBT;
    private javax.swing.JButton btnIMGAVL;
    private javax.swing.JButton btnInOrdAVL;
    private javax.swing.JButton btnModAVL;
    private javax.swing.JButton btnPostAVL;
    private javax.swing.JButton btnPreOrnAVL;
    private javax.swing.JButton buscarBBT;
    private javax.swing.JButton cargarAVL;
    private javax.swing.JMenuItem cargarArchivoAVL;
    private javax.swing.JMenuItem cargarArchivoBBT;
    private javax.swing.JButton eliminarBBT;
    private javax.swing.JButton grabarAVL;
    private javax.swing.JLabel imgBBT;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton inOrdBBT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton postBBT;
    private javax.swing.JButton preOrdBBT;
    private javax.swing.JTextField txtAVL;
    private javax.swing.JTextArea txtAreAVL;
    private javax.swing.JTextArea txtArea1;
    private javax.swing.JTextField txtBTT;
    // End of variables declaration//GEN-END:variables
}
